language: node_js
jobs:
  include:
    - stage: test
      node_js:
        - 12.13.1
      script:
        - npm test
    - stage: release
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: 'true'
        script:
          - npx semantic-release
branches:
  only:
    - master
    - /^greenkeeper/.*$/
    - /^mkpr/.*$/
    - /^npm-template-sync/.*$/
